name: CI

# Controls when the action will run. 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: evzijst/fpgatools:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build iCE40 FPGA bitstream
        run: make pong.bin

      - name: Run cocotb test simulations
        run: make

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'build/test-results/results_*.xml'

      - name: Lint
        run: make lint || true
