name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: evzijst/fpgatools:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build iCE40 FPGA bitstream
        run: |
          make pong.bin
          make ballsim
          make mathsim
          make sim

      - name: Run cocotb test simulations
        run: |
          make ballsim mathsim sim

      - name: Lint
        run: make lint
